action_names_dict = {
    "A": "gatherWoodLog",
    "B": "craftPlanks",
    "C": "craftCraftingTable",
    "D": "craftSticks",
    "E": "craftFence",
    "F": "craftFenceGate",
    "G": "craftWoodenAxe",
    "H": "craftWoodenHoe",
    "I": "craftWoodenShovel",
    "J": "craftWoodenSword",
    "K": "craftWoodenPickaxe",
    "L": "gatherCoalOre",
    "M": "gatherStone",
    "N": "craftStoneAxe",
    "O": "craftStoneHoe",
    "P": "craftStoneShovel",
    "Q": "craftStoneSword",
    "R": "craftStonePickaxe",
    "S": "craftFurnace",
    "T": "mineIronOre",
    "U": "smeltRawIron",
    "V": "craftIronAxe",
    "W": "craftIronHoe",
    "X": "craftIronShovel",
    "Y": "craftIronSword",
    "Z": "craftIronPickaxe",
    "AA": "mineGoldOre",
    "AB": "mineDiamondOre",
    "AC": "craftDiamondAxe",
    "AD": "craftDiamondHoe",
    "AE": "craftDiamondPickaxe",
    "AF": "craftDiamondShovel",
    "AG": "craftDiamondSword",
    "AH": "gatherDirt",
    "AI": "gatherSand",
    "AJ": "smeltRawGold",
    "AK": "craftGoldenAxe",
    "AL": "craftGoldenHoe",
    "AM": "craftGoldenPickaxe",
    "AN": "craftGoldenShovel",
    "AO": "craftGoldenSword"
}

action_names_rev_dict = {
    "gatherWoodLog": "A",
    "craftPlanks": "B",
    "craftCraftingTable": "C",
    "craftSticks": "D",
    "craftFence": "E",
    "craftFenceGate": "F",
    "craftWoodenAxe": "G",
    "craftWoodenHoe": "H",
    "craftWoodenShovel": "I",
    "craftWoodenSword": "J",
    "craftWoodenPickaxe": "K",
    "gatherCoalOre": "L",
    "gatherStone": "M",
    "craftStoneAxe": "N",
    "craftStoneHoe": "O",
    "craftStoneShovel": "P",
    "craftStoneSword": "Q",
    "craftStonePickaxe": "R",
    "craftFurnace": "S",
    "mineIronOre": "T",
    "smeltRawIron": "U",
    "craftIronAxe": "V",
    "craftIronHoe": "W",
    "craftIronShovel": "X",
    "craftIronSword": "Y",
    "craftIronPickaxe": "Z",
    "mineGoldOre": "AA",
    "mineDiamondOre": "AB",
    "craftDiamondAxe": "AC",
    "craftDiamondHoe": "AD",
    "craftDiamondPickaxe": "AE",
    "craftDiamondShovel": "AF",
    "craftDiamondSword": "AG",
    "gatherDirt": "AH",
    "gatherSand": "AI",
    "smeltRawGold": "AJ",
    "craftGoldenAxe": "AK",
    "craftGoldenHoe": "AL",
    "craftGoldenPickaxe": "AM",
    "craftGoldenShovel": "AN",
    "craftGoldenSword": "AO"
}

material_names_dict = {
    'a': 'log',
    'b': 'planks',
    'c': 'crafting_table',
    'd': 'stick',
    'e': 'wooden_pickaxe',
    'f': 'cobblestone',
    'g': 'stone_pickaxe',
    'h': 'raw_iron',
    'i': 'furnace',
    'j': 'iron_ingot',
    'k': 'iron_pickaxe',
    'l': 'diamond',
    'm': 'diamond_axe',
    'n': 'diamond_hoe',
    'o': 'diamond_pickaxe',
    'p': 'diamond_shovel',
    'q': 'diamond_sword',
    'r': 'fence',
    's': 'fence_gate',
    't': 'golden_axe',
    'u': 'golden_hoe',
    'v': 'golden_pickaxe',
    'w': 'golden_shovel',
    'x': 'golden_sword',
    'y': 'iron_axe',
    'z': 'iron_hoe',
    'aa': 'iron_shovel',
    'ab': 'iron_sword',
    'ac': 'stone_axe',
    'ad': 'stone_hoe',
    'ae': 'stone_shovel',
    'af': 'stone_sword',
    'ag': 'wooden_axe',
    'ah': 'wooden_hoe',
    'ai': 'wooden_shovel',
    'aj': 'wooden_sword',
    'ak': 'coal',
    'al': 'dirt',
    'am': 'raw_gold',
    'an': 'sand',
    'ao': 'gold_ingot'
}

material_names_rev_dict = {
    'log': 'a',
    'planks': 'b',
    'crafting_table': 'c',
    'stick': 'd',
    'wooden_pickaxe': 'e',
    'cobblestone': 'f',
    'stone_pickaxe': 'g',
    'raw_iron': 'h',
    'furnace': 'i',
    'iron_ingot': 'j',
    'iron_pickaxe': 'k',
    'diamond': 'l',
    'diamond_axe': 'm',
    'diamond_hoe': 'n',
    'diamond_pickaxe': 'o',
    'diamond_shovel': 'p',
    'diamond_sword': 'q',
    'fence': 'r',
    'fence_gate': 's',
    'golden_axe': 't',
    'golden_hoe': 'u',
    'golden_pickaxe': 'v',
    'golden_shovel': 'w',
    'golden_sword': 'x',
    'iron_axe': 'y',
    'iron_hoe': 'z',
    'iron_shovel': 'aa',
    'iron_sword': 'ab',
    'stone_axe': 'ac',
    'stone_hoe': 'ad',
    'stone_shovel': 'ae',
    'stone_sword': 'af',
    'wooden_axe': 'ag',
    'wooden_hoe': 'ah',
    'wooden_shovel': 'ai',
    'wooden_sword': 'aj',
    'coal': 'ak',
    'dirt': 'al',
    'raw_gold': 'am',
    'sand': 'an',
    'gold_ingot': 'ao'
}

unlock = {
    "a": [
        "B"
    ],
    "b": [
        "C",
        "D"
    ],
    "c": [
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K"
    ],
    "d": [],
    "e": [
        "L",
        "M"
    ],
    "f": [
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S"
    ],
    "g": [
        "T"
    ],
    "h": [
        "U"
    ],
    "i": [],
    "j": [
        "V",
        "W",
        "X",
        "Y",
        "Z"
    ],
    "k": [
        "AA",
        "AB"
    ],
    "l": [
        "AC",
        "AD",
        "AE",
        "AF",
        "AG"
    ],
    "m": [],
    "n": [],
    "o": [],
    "p": [],
    "q": [],
    "r": [],
    "s": [],
    "t": [],
    "u": [],
    "v": [],
    "w": [],
    "x": [],
    "y": [],
    "z": [],
    "aa": [],
    "ab": [],
    "ac": [],
    "ad": [],
    "ae": [],
    "af": [],
    "ag": [],
    "ah": [],
    "ai": [
        "AH",
        "AI"
    ],
    "aj": [],
    "ak": [],
    "al": [],
    "am": [
        "AJ"
    ],
    "an": [],
    "ao": [
        "AK",
        "AL",
        "AM",
        "AN",
        "AO"
    ]
}
